# Render Blueprint for SaudiCord
# Made With Love By SirAbody
# MongoDB Atlas Configuration

services:
  # Combined Backend + Frontend Service
  - type: web
    name: saudicord
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: cd server && node server-mongodb.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://abood3alshrary_db_user:23U4pKSr6zNEnf0C@saudicord.sfzfre8.mongodb.net/saudicord?retryWrites=true&w=majority&appName=saudicord
      - key: JWT_SECRET
        value: saudicord-secret-key-2024
      - key: CLIENT_URL
        value: https://saudicord.onrender.com
      - key: USE_MONGODB
        value: true
      - key: RESET_DB
        value: false
